[layout]
default_column_width = 1

[appearance]
background_color = "#1e1a2b"
prefer_no_csd = true

[wallpaper]
image = "/defaults/wallpaper.png"
mode = "fill"

[autostart]
commands = [
  "spawn scoot-bar-look",
]

[binds]
"alt+Return" = "spawn foot"
"super+Return" = "spawn foot"
"alt+t" = "spawn foot"
"super+t" = "spawn foot"
"alt+d" = "spawn fuzzel"
"super+d" = "spawn fuzzel"
"alt+q" = "close"
"super+q" = "close"
"alt+h" = "focus-column left"
"alt+l" = "focus-column right"
"super+h" = "focus-column left"
"super+l" = "focus-column right"
