// wsbridge: single-port HTTP file server + WebSocket-to-TCP proxy.
//
// Replaces python websockify for the try-scoot image: serves the noVNC web
// tree over HTTP and proxies WebSocket connections through to the VNC
// listener on the same port, so one TCP port carries the whole desktop.
// Pure Go standard library, built CGO_ENABLED=0: the runtime closure is just
// this static binary (no python, no numpy).
//
// Wire protocol notes (from RFC 6455 + websockify behavior):
//   - noVNC requests Sec-WebSocket-Protocol: binary; we echo it, else the
//     client aborts the connection.
//   - client->server frames are masked (unmask here); server->client frames
//     go out unmasked binary, one frame per TCP read, like websockify.
//   - ping -> pong, close -> echoed close, continuation frames reassembled.
package main

import (
	"crypto/sha1"
	"encoding/base64"
	"flag"
	"io"
	"log"
	"net"
	"net/http"
	"strings"
)

var (
	listenAddr = flag.String("listen", "0.0.0.0:6080", "HTTP+WS listen address")
	targetAddr = flag.String("target", "localhost:5900", "TCP target for proxied frames")
	webDir     = flag.String("web", "", "directory of static files to serve")
)

const wsGUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

func main() {
	flag.Parse()
	if *webDir == "" {
		log.Fatal("wsbridge: -web directory is required")
	}
	http.HandleFunc("/", serveWSOrFiles)
	log.Printf("wsbridge: http+ws %s -> tcp %s (web %s)", *listenAddr, *targetAddr, *webDir)
	log.Fatal(http.ListenAndServe(*listenAddr, nil))
}

func serveWSOrFiles(w http.ResponseWriter, r *http.Request) {
	if isWSUpgrade(r) {
		proxyWS(w, r)
		return
	}
	// Plain HTTP: the noVNC web client. index.html is pre-generated by the
	// service run script; fall back to vnc.html for bare /vnc* paths handled
	// by the file server itself.
	http.FileServer(http.Dir(*webDir)).ServeHTTP(w, r)
}

func isWSUpgrade(r *http.Request) bool {
	return strings.EqualFold(r.Header.Get("Connection"), "Upgrade") ||
		strings.Contains(strings.ToLower(r.Header.Get("Connection")), "upgrade") &&
			strings.EqualFold(r.Header.Get("Upgrade"), "websocket")
}

// proxyWS performs the server side of the RFC 6455 opening handshake, then
// splices the connection to the TCP target in both directions.
func proxyWS(w http.ResponseWriter, r *http.Request) {
	key := r.Header.Get("Sec-WebSocket-Key")
	if key == "" {
		http.Error(w, "missing Sec-WebSocket-Key", http.StatusBadRequest)
		return
	}
	proto := ""
	for _, p := range strings.Split(r.Header.Get("Sec-WebSocket-Protocol"), ",") {
		if strings.TrimSpace(p) == "binary" {
			proto = "binary"
		}
	}

	hj, ok := w.(http.Hijacker)
	if !ok {
		http.Error(w, "hijack unsupported", http.StatusInternalServerError)
		return
	}
	conn, rw, err := hj.Hijack()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	accept := wsAccept(key)
	var hs strings.Builder
	hs.WriteString("HTTP/1.1 101 Switching Protocols\r\n")
	hs.WriteString("Upgrade: websocket\r\n")
	hs.WriteString("Connection: Upgrade\r\n")
	hs.WriteString("Sec-WebSocket-Accept: " + accept + "\r\n")
	if proto != "" {
		hs.WriteString("Sec-WebSocket-Protocol: " + proto + "\r\n")
	}
	hs.WriteString("\r\n")
	if _, err := io.WriteString(rw, hs.String()); err != nil {
		conn.Close()
		return
	}
	if err := rw.Flush(); err != nil {
		conn.Close()
		return
	}

	backend, err := net.Dial("tcp", *targetAddr)
	if err != nil {
		// 101 already sent; report via a close frame with 1014 (bad
		// gateway) and drop. The noVNC client surfaces this as a failed
		// connect, same as websockify refusing the target.
		writeFrame(conn, 0x8, []byte{0x03, 0xF6})
		conn.Close()
		return
	}
	go tcpToWS(backend, conn)
	wsToTCP(conn, backend)
}

func wsAccept(key string) string {
	h := sha1.New()
	h.Write([]byte(key + wsGUID))
	return base64.StdEncoding.EncodeToString(h.Sum(nil))
}

// wsToTCP runs on the calling goroutine: parse client frames, forward binary
// payloads to the backend. Returns when either side is done.
func wsToTCP(conn net.Conn, backend net.Conn) {
	defer conn.Close()
	defer backend.Close()
	for {
		op, payload, err := readMessage(conn)
		if err != nil {
			return
		}
		switch op {
		case 0x8: // close: echo and stop
			writeFrame(conn, 0x8, payload)
			return
		case 0x1, 0x2: // text/binary: RFB uses binary; forward either
			if _, err := backend.Write(payload); err != nil {
				return
			}
		}
	}
}

// tcpToWS wraps each backend read in one unmasked binary frame.
func tcpToWS(backend net.Conn, conn net.Conn) {
	defer backend.Close()
	defer conn.Close()
	buf := make([]byte, 65536)
	for {
		n, err := backend.Read(buf)
		if n > 0 {
			if werr := writeFrame(conn, 0x2, buf[:n]); werr != nil {
				return
			}
		}
		if err != nil {
			// Backend closed: clean close on the WS side.
			writeFrame(conn, 0x8, []byte{0x03, 0xE8})
			return
		}
	}
}

// readMessage reads one whole message, reassembling fragmented data frames
// and answering pings inline. Returns the data opcode (0x1/0x2, or 0x8 for
// close) and the full payload.
func readMessage(conn net.Conn) (byte, []byte, error) {
	var msg []byte
	var msgOp byte
	for {
		fin, op, payload, err := readFrame(conn)
		if err != nil {
			return 0, nil, err
		}
		switch op {
		case 0x8: // close
			return op, payload, nil
		case 0x9: // ping: pong with same body, keep reading
			_ = writeFrame(conn, 0xA, payload)
		case 0xA: // pong: ignore
		case 0x1, 0x2: // data frame starts a message
			msgOp = op
			msg = append(msg, payload...)
			if fin {
				return msgOp, msg, nil
			}
		case 0x0: // continuation
			msg = append(msg, payload...)
			if fin {
				return msgOp, msg, nil
			}
		}
	}
}

// readFrame parses one RFC 6455 frame. Returns final flag, opcode and
// (unmasked) payload. Control frames are limited to 125 bytes by the
// protocol and are always final.
func readFrame(conn net.Conn) (bool, byte, []byte, error) {
	var hdr [2]byte
	if _, err := io.ReadFull(conn, hdr[:]); err != nil {
		return false, 0, nil, err
	}
	fin := hdr[0]&0x80 != 0
	op := hdr[0] & 0x0F
	masked := hdr[1]&0x80 != 0
	n := int64(hdr[1] & 0x7F)
	switch n {
	case 126:
		var ext [2]byte
		if _, err := io.ReadFull(conn, ext[:]); err != nil {
			return false, 0, nil, err
		}
		n = int64(ext[0])<<8 | int64(ext[1])
	case 127:
		var ext [8]byte
		if _, err := io.ReadFull(conn, ext[:]); err != nil {
			return false, 0, nil, err
		}
		n = 0
		for _, b := range ext {
			n = n<<8 | int64(b)
		}
	}
	var mask [4]byte
	if masked {
		if _, err := io.ReadFull(conn, mask[:]); err != nil {
			return false, 0, nil, err
		}
	}
	payload := make([]byte, n)
	if _, err := io.ReadFull(conn, payload); err != nil {
		return false, 0, nil, err
	}
	if masked {
		for i := range payload {
			payload[i] ^= mask[i%4]
		}
	}
	return fin, op, payload, nil
}

// writeFrame emits one server-to-client (unmasked) frame.
func writeFrame(conn net.Conn, op byte, payload []byte) error {
	n := len(payload)
	var hdr []byte
	hdr = append(hdr, 0x80|op)
	switch {
	case n < 126:
		hdr = append(hdr, byte(n))
	case n < 65536:
		hdr = append(hdr, 126, byte(n>>8), byte(n))
	default:
		hdr = append(hdr, 127, 0, 0, 0, 0, byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	}
	if _, err := conn.Write(hdr); err != nil {
		return err
	}
	if n == 0 {
		return nil
	}
	_, err := conn.Write(payload)
	return err
}
